kind: pipeline
type: docker
name: default

steps:
- name: build
  image: electronuserland/builder:wine-mono
  commands:
  - yarn
  - yarn build

- name: view
  image: node
  commands:
  - node view.js

- name: release
  image: node
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - export PROJECT_VERSION=$(node -p "require('./package.json').version")
  - echo $GITHUB_TOKEN
  - echo $PROJECT_VERSION
  - yarn github-release upload --owner Loquicom --repo Wikipath --tag $PROJECT_VERSION --release-name $PROJECT_VERSION "wikipath-0.0.1-win.zip" "wikipath-0.0.1.tar.gz" "wikipath_0.0.1_amd64.deb" 