kind: pipeline
type: docker
name: default

steps:
- name: build
  image: electronuserland/builder:wine-mono
  commands:
  - yarn
  - yarn build

- name: release
  image: node
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - export PROJECT_VERSION=$(node -p "require('./package.json').version")
  - yarn github-release upload --owner Loquicom --repo Wikipath --prerelease true --tag $PROJECT_VERSION --release-name $PROJECT_VERSION "dist/wikipath_$${PROJECT_VERSION}_amd64.deb" "dist/wikipath-$${PROJECT_VERSION}.tar.gz" "dist/wikipath $${PROJECT_VERSION}.exe" "dist/squirrel-windows/wikipath Setup $${PROJECT_VERSION}.exe" "dist/wikipath-$${PROJECT_VERSION}-win.zip" 

trigger:
  branch:
  - master
  event:
  - push  