kind: pipeline
type: docker
name: default

steps:
- name: build
  image: electronuserland/builder:wine-mono
  commands:
  - yarn
  - yarn build

- name: view
  image: node
  commands:
  - yarn view

trigger:
  branch:
  - master
  event:
  - push  