kind: pipeline
type: docker
name: default

steps:
- name: name
  image: node
  commands:
  - export PROJECT_VERSION=$(node -p "require('./package.json').version")
  - echo $PROJECT_VERSION
  - echo "dist/wikipath_${PROJECT_VERSION}_amd64.deb"
  - echo "dist/wikipath_$${PROJECT_VERSION}_amd64.deb"

- name: build
  image: electronuserland/builder:wine-mono
  commands:
  - yarn
  - yarn build

- name: view
  image: node
  commands:
  - node view.js

- name: release
  image: node
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - export PROJECT_VERSION=$(node -p "require('./package.json').version")
  - yarn github-release upload --owner Loquicom --repo Wikipath --tag $PROJECT_VERSION --release-name $PROJECT_VERSION "dist/wikipath_${PROJECT_VERSION}_amd64.deb" "dist/wikipath-${PROJECT_VERSION}.tar.gz" "dist/wikipath ${PROJECT_VERSION}.exe" "dist/squirrel-windows/wikipath Setup ${PROJECT_VERSION}.exe" "dist/wikipath-${PROJECT_VERSION}-win.zip" 

trigger:
  branch:
  - master